import { IChildren } from "@/shared/types";
import { appTitle } from "@/shared/utils";
import "bootstrap/dist/css/bootstrap.min.css";
import type { Metadata, Viewport } from "next";

export const metadata: Metadata = {
  title: appTitle(),
  description: "Generated by create next app",
  alternates: {
    canonical: process.env.NEXT_PUBLIC_CANONICAL_URL,
  },
};

export const viewport: Viewport = {
  themeColor: "#0d6efd",
  colorScheme: "light",
};

const RootLayout = ({ children }: IChildren) => {
  return (
    <html lang="en" className="h-100">
      <body className="d-flex flex-column h-100 bg-light overflow-x-hidden overflow-y-auto">
        <main className="flex-fill">{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
